### ISSUE TITLE
Use timestamps from the transform nodes

### ISSUE THREAD

**Issue by mholden8** [PerkTutor/TransformRecorder#14]
Now, the transforms are recorded using the system clock. There is an uncertainty in the accuracy of current timestamps up to about 0.05 s. There is a way to store attributes in all MRML nodes, and probably OpenIGTLinkIF sets the timestamp in the transform nodes. Recording these by TransformRecorder would be a more accurate solution.

**Comment by matthewsholden** [comment]
No longer relevant - recording behaviour is controlled by Sequences modules.
