### ISSUE TITLE
Update transform buffer when transform record time changes

### ISSUE THREAD

**Issue by mholden8** [PerkTutor/TransformRecorder#23]
When a vtkTransformRecord is added to a transform buffer, it is put in the appropriate order in the transform buffer. If a vtkTransformRecord is already in the transform buffer and then its time is modified, the transform buffer should be re-ordered. Whenever a vtkTransformRecord's time is modified, the transform buffer should move that vtkTransformRecord to the appropriate order.

**Comment by matthewsholden** [comment]
This issue is no longer relevant due to use of Sequences nodes instead of Transform Buffer nodes.
